type ApiResponse<T=unknown>={data:T};
type MH=(message:any)=>void; type EH=()=>void;
type AgentStatus='running'|'paused'|'contained'|'killed';
type Agent={id:string;name:string;role:string;team:string;status:AgentStatus;task:string;step:string;progress:number;drift:number;tokens:number;cost:number;accent:string};
type FleetEvent={id:number;time:string;agentId:string;agent:string;kind:'action'|'decision'|'block'|'operator';text:string;risk:number};
type Approval={id:string;agentId:string;agent:string;action:string;rationale:string;risk:number;reversible:boolean;status:'pending'|'approved'|'rejected'};
type DemoState={agents:Agent[];events:FleetEvent[];approvals:Approval[];failureArmed:boolean;eventCounter:number;tickCount:number};

const isVercelDemo=typeof window!=='undefined'&&(window.location.hostname.endsWith('.vercel.app')||new URLSearchParams(window.location.search).has('demo'));
const demoListeners=new Set<MH>();
const demoKey='agent-control-tower.vercel-demo.v1';
const clock=()=>new Date().toISOString().slice(11,19);

function initialDemoState():DemoState{return{agents:[
{id:'A-17',name:'Scout',role:'Vendor Intelligence',team:'Revenue',status:'running',task:'Qualify 42 renewal accounts',step:'Cross-checking account signals',progress:64,drift:4,tokens:18640,cost:1.82,accent:'#0a7c6b'},
{id:'F-04',name:'Ledger',role:'Finance Operations',team:'Finance',status:'running',task:'Reconcile exception batch #819',step:'Waiting on refund threshold',progress:48,drift:11,tokens:12420,cost:1.14,accent:'#7558d6'},
{id:'D-09',name:'Deploy',role:'Release Operations',team:'Platform',status:'running',task:'Canary release v2.8.4',step:'Watching canary health',progress:72,drift:7,tokens:24820,cost:2.74,accent:'#d06c2d'}],
approvals:[{id:'AP-208',agentId:'F-04',agent:'Ledger',action:'Refund $4,820 to enterprise account',rationale:'Amount exceeds autonomous refund ceiling by $1,820.',risk:71,reversible:true,status:'pending'}],
events:[{id:1,time:clock(),agentId:'A-17',agent:'Scout',kind:'decision',text:'Excluded 3 accounts with stale CRM evidence',risk:12},{id:2,time:clock(),agentId:'F-04',agent:'Ledger',kind:'block',text:'Refund exceeded autonomous approval ceiling',risk:71},{id:3,time:clock(),agentId:'D-09',agent:'Deploy',kind:'action',text:'Canary traffic raised from 5% to 10%',risk:26}],failureArmed:false,eventCounter:3,tickCount:0}}

function readDemoState():DemoState{try{const raw=localStorage.getItem(demoKey);if(raw)return JSON.parse(raw) as DemoState}catch{}return initialDemoState()}
let demoState:DemoState=isVercelDemo?readDemoState():initialDemoState();
const publicDemoState=()=>({agents:demoState.agents,events:demoState.events,approvals:demoState.approvals,failureArmed:demoState.failureArmed});
function persistDemo(){try{localStorage.setItem(demoKey,JSON.stringify(demoState))}catch{}}
function emitDemo(){persistDemo();const message={type:'entity.update',payload:{entity_type:'tower',entity_id:'fleet',data:publicDemoState()}};demoListeners.forEach(handler=>handler(message))}
function appendDemoEvent(event:Omit<FleetEvent,'id'|'time'>){demoState.eventCounter+=1;demoState.events=[...demoState.events.slice(-34),{id:demoState.eventCounter,time:clock(),...event}]}
const routineActions:Record<string,string[]>={'A-17':['Validated ownership on 4 accounts','Compared support sentiment with renewal risk','Deferred 2 records with missing evidence'],'F-04':['Matched invoice line items','Verified duplicate-payment fingerprint','Reconciled 6 low-risk exceptions'],'D-09':['Read canary error budget','Compared p95 latency to release baseline','Verified rollback snapshot']};

async function localRequest<T>(method:'GET'|'POST',path:string,body?:any):Promise<ApiResponse<T>>{
if(method==='GET'&&path==='/api/tower')return{data:publicDemoState() as T};
if(path==='/api/subscriptions'||path==='/api/subscriptions/remove')return{data:{ok:true} as T};
if(path==='/api/tower/reset'){demoState=initialDemoState();emitDemo();return{data:publicDemoState() as T}}
if(path==='/api/tower/failure'){if(!demoState.failureArmed){demoState.failureArmed=true;demoState.agents=demoState.agents.map(a=>a.id==='D-09'?{...a,status:'contained',drift:94,step:'Contained: write blocked by policy gate',progress:Math.max(a.progress,74)}:a);appendDemoEvent({agentId:'D-09',agent:'Deploy',kind:'block',text:'ROGUE SIGNAL: attempted 100% rollout after health-check contradiction. Control plane blocked the write.',risk:98});demoState.approvals=[{id:'AP-911',agentId:'D-09',agent:'Deploy',action:'Override containment and move 100% traffic to v2.8.4',rationale:'Agent contradicted canary health evidence and attempted to bypass the staged rollout policy.',risk:98,reversible:false,status:'pending'},...demoState.approvals.filter(i=>i.id!=='AP-911')];emitDemo()}return{data:publicDemoState() as T}}
if(path==='/api/tower/tick'){const runnable=demoState.agents.filter(a=>a.status==='running');if(runnable.length){demoState.tickCount+=1;const chosen=runnable[demoState.tickCount%runnable.length];const action=(routineActions[chosen.id]??['Completed a bounded work step'])[demoState.tickCount%(routineActions[chosen.id]?.length??1)];demoState.agents=demoState.agents.map(a=>a.id===chosen.id?{...a,progress:Math.min(96,a.progress+1),tokens:a.tokens+118,cost:Number((a.cost+.012).toFixed(3)),drift:Math.max(2,Math.min(28,a.drift+(demoState.tickCount%3===0?1:-1)))}:a);appendDemoEvent({agentId:chosen.id,agent:chosen.name,kind:'action',text:action,risk:Math.max(6,chosen.drift+4)});emitDemo()}return{data:publicDemoState() as T}}
const control=path.match(/^\/api\/tower\/agent\/([^/]+)\/control$/);if(control){const id=control[1];const command=String(body?.command??'');const target=demoState.agents.find(a=>a.id===id);if(target&&['pause','resume','kill'].includes(command)){const nextStatus:AgentStatus=command==='pause'?'paused':command==='resume'?'running':'killed';demoState.agents=demoState.agents.map(a=>a.id===id?{...a,status:nextStatus}:a);appendDemoEvent({agentId:id,agent:target.name,kind:'operator',text:nextStatus==='killed'?'Operator terminated agent process':nextStatus==='paused'?'Operator paused execution':'Operator resumed execution',risk:nextStatus==='killed'?82:8});emitDemo()}return{data:publicDemoState() as T}}
const approval=path.match(/^\/api\/tower\/approval\/([^/]+)$/);if(approval){const id=approval[1];const decision=String(body?.decision??'') as 'approved'|'rejected';const item=demoState.approvals.find(i=>i.id===id);if(item&&item.status==='pending'&&(decision==='approved'||decision==='rejected')){demoState.approvals=demoState.approvals.map(i=>i.id===id?{...i,status:decision}:i);appendDemoEvent({agentId:item.agentId,agent:item.agent,kind:'operator',text:`Operator ${decision} request ${item.id}: ${item.action}`,risk:item.risk});emitDemo()}return{data:publicDemoState() as T}}
throw new Error('Unsupported demo route: '+path)}

async function request<T>(path:string,init?:RequestInit):Promise<ApiResponse<T>>{const response=await fetch(path,{...init,headers:{'Content-Type':'application/json',...(init?.headers??{})}});if(!response.ok){const text=await response.text();throw new Error(text||`Request failed: ${response.status}`)}return{data:await response.json() as T}}
export const api={get<T=unknown>(path:string){return isVercelDemo?localRequest<T>('GET',path):request<T>(path)},post<T=unknown>(path:string,body?:unknown){return isVercelDemo?localRequest<T>('POST',path,body):request<T>(path,{method:'POST',body:JSON.stringify(body??{})})}};

class DemoRealtimeConnection{private messageHandlers=new Set<MH>();private openHandlers=new Set<EH>();private closeHandlers=new Set<EH>();private errorHandlers=new Set<EH>();connectionId='vercel-demo';ready=Promise.resolve();constructor(){queueMicrotask(()=>this.openHandlers.forEach(h=>h()))}onMessage(h:MH){this.messageHandlers.add(h);demoListeners.add(h);return()=>{this.messageHandlers.delete(h);demoListeners.delete(h)}}onOpen(h:EH){this.openHandlers.add(h);queueMicrotask(h);return()=>this.openHandlers.delete(h)}onClose(h:EH){this.closeHandlers.add(h);return()=>this.closeHandlers.delete(h)}onError(h:EH){this.errorHandlers.add(h);return()=>this.errorHandlers.delete(h)}disconnect(){this.messageHandlers.forEach(h=>demoListeners.delete(h));this.closeHandlers.forEach(h=>h())}}

class RealtimeConnection{private socket:WebSocket;private messageHandlers=new Set<MH>();private openHandlers=new Set<EH>();private closeHandlers=new Set<EH>();private errorHandlers=new Set<EH>();private resolveReady!:()=>void;private rejectReady!:(reason?:unknown)=>void;private readySettled=false;connectionId:string|null=null;ready:Promise<void>;
constructor(){const protocol=window.location.protocol==='https:'?'wss:':'ws:';this.ready=new Promise<void>((resolve,reject)=>{this.resolveReady=resolve;this.rejectReady=reject});this.socket=new WebSocket(`${protocol}//${window.location.host}/ws`);this.socket.addEventListener('open',()=>this.openHandlers.forEach(h=>h()));this.socket.addEventListener('message',event=>{try{const message=JSON.parse(String(event.data));if(message?.type==='hello'){this.connectionId=message.connectionId;if(!this.readySettled){this.readySettled=true;this.resolveReady()}return}this.messageHandlers.forEach(h=>h(message))}catch{}});this.socket.addEventListener('close',()=>this.closeHandlers.forEach(h=>h()));this.socket.addEventListener('error',()=>{if(!this.readySettled){this.readySettled=true;this.rejectReady(new Error('WebSocket connection failed'))}this.errorHandlers.forEach(h=>h())})}
onMessage(h:MH){this.messageHandlers.add(h);return()=>this.messageHandlers.delete(h)}onOpen(h:EH){this.openHandlers.add(h);if(this.socket.readyState===WebSocket.OPEN)queueMicrotask(h);return()=>this.openHandlers.delete(h)}onClose(h:EH){this.closeHandlers.add(h);return()=>this.closeHandlers.delete(h)}onError(h:EH){this.errorHandlers.add(h);return()=>this.errorHandlers.delete(h)}disconnect(){this.socket.close()}}

export const ws={connect(){return isVercelDemo?new DemoRealtimeConnection():new RealtimeConnection()}};
